### ISSUE TITLE
Related 'Now we can access any review's associated game directly by using this new instance method:' Section Has Duplicate Sections

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-3-active-record-associations-one-to-many#10]
### Canvas Link

https://learning.flatironschool.com/courses/5286/assignments/172709?module_item_id=376777

### Concern

These two sections are identical:

**First Section:**
Then run rake console again. Now we can access any review's associated game directly by using this new instance method:

```
Review.first.game
# => #<Game:0x00007ffc2801e4e8 id: 1, title: "Metroid Prime", ...>
Review.last.game
# => #<Game:0x00007f9c68130d38 id: 50, title: "Max Payne", ...>
```

**Second Section:**
Now, exit the console and open it again to reload your code, and try using the #game instance method:

```
Review.first.game
# => #<Game:0x00007ffc2801e4e8 id: 1, title: "Metroid Prime", ...>
Review.last.game
# => #<Game:0x00007f9c68130d38 id: 50, title: "Max Payne", ...>
```

### Suggested Changes

Needs to be revised as this section is a bit awkward as it literally has the same exact output with no difference.

**Comment by jlboba** [comment]
Hello, thank you for your suggestion and feedback! In this particular case, however, the output is intentionally identical. It's meant to showcase the two ways of getting to this same exact output (writing your own custom method vs. using the ActiveRecord `belongs_to` macro), where using Active Record is quicker. 

Underneath this section, it highlights this:

> As you can see, this method does the same job as our custom instance method, but with less work on our part. Thanks, Active Record!

As such, I'll be closing this issue. If you still have further suggestions however, feel free to reopen. Thanks!
