### ISSUE TITLE
learn-co gem missing

### ISSUE THREAD

**Issue by astania** [learn-co-curriculum/phase-3-active-record-associations-one-to-many#2]
### Canvas Link

https://learning.flatironschool.com/courses/4601/assignments/147558?module_item_id=311207

### Concern

This lesson instructs us to run "learn test", but when you do that, you get an error that the learn-co gem is not in the bundle for this lesson (I did run bundle install before running learn test). 

### Additional Context

Here is the error message I received: 

Traceback (most recent call last):
        4: from /usr/share/rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'
        3: from /usr/share/rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
        2: from /usr/share/rvm/gems/ruby-2.7.4/bin/learn:25:in `<main>'
        1: from /usr/share/rvm/gems/ruby-2.7.4/gems/bundler-2.3.10/lib/bundler/rubygems_integration.rb:347:in `block in replace_bin_path'
/usr/share/rvm/gems/ruby-2.7.4/gems/bundler-2.3.10/lib/bundler/rubygems_integration.rb:319:in `block in replace_bin_path': can't find executable learn for gem learn-co. learn-co is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)

### Suggested Changes

Remove references to running learn test from this lesson, or add the learn-co gem to the bundle.

**Comment by AlveeM** [comment]
Hi @astania, thanks for submitting the issue.

We couldn't replicate the issue on our end. Please reach out to your coach or instructor for help.

If you have any further notes or clarifications after meeting with them, feel free to comment here or submit a new issue.
