### ISSUE TITLE
Column values incorrect

### ISSUE THREAD

**Issue by ohsean812** [learn-co-curriculum/phase-3-active-record-associations-one-to-many#5]
### Canvas Link

https://learning.flatironschool.com/courses/5208/assignments/199386?module_item_id=451189

### Concern

Not a major issue, but I believe the values for the "genre" column and "platform" column were switched under "The Game Model" section.  It says {genre: Switch} and {platform: Action-adventure}, but I believe they should read {genre: Action-adventure} and {platform: Switch} instead.

**Comment by lizbur10** [comment]
Nice catch @ohsean812! Thanks for bringing this to our attention - it has now been fixed 💙
